- name: Копируем дефолтный /etc/apt/sources.list в /etc/apt/sources.list_bak
  copy:
    src: "/etc/apt/sources.list"
    dest: "/etc/apt/sources.list_bak"
    remote_src: yes

- name: Удаляем дефолтный файл /etc/apt/sources.list
  file:
    path: "/etc/apt/sources.list"
    state: absent

- name: Копируем Nexus-D-002_ubuntu_20.list если ОС Ubuntu 20.04
  copy:
    src: "{{ role_path }}/files/Nexus-D-002_ubuntu_20.list"
    dest: "/etc/apt/sources.list"
  when:
    - os_distrib == 'ubuntu'