# - name: Устанавливаем таймзону MSK
#   timezone:
#     name: Europe/Moscow

- name: Подправляем /etc/hosts (только Ubuntu)
  template:
    src: "{{ role_path }}/templates/hosts.j2"
    dest: /etc/hosts
    owner: root
    mode: 0644
  when:
    - os_distrib == 'ubuntu'

- name: Устанавливаем hostname
  hostname:
    name: "{{ inventory_hostname_short }}"
    use: systemd

