- name: Удостоверяемся, что существует /etc/docker
  file:
    path: /etc/docker
    state: directory
    mode: '0755'
- name: Подсовываем daemon.json (только если уже не существует)
  copy:
    src: "{{ role_path }}/files/docker_daemon.json"
    dest: /etc/docker/daemon.json
    mode: '0644'
    force: no
